#!/bin/bash

# Title: An Advanced Button Payload 
#
# Description: A more advanced button payload that will use the button to change the LED pattern based on how many times the button was pressed on the Packet Squirrel
#
# Author: @H311oWoR1d1337 
#
# Props: Michael Kershaw

# Setting the Squirrel's Network Mode to NAT
NETMODE NAT

# Setting the LED to start as Blue and flash Very Fast
LED B VERYFAST

# Setting the button to wait indefinitely for a press and have it not affect the LED using the environment variable NO_LED=1 meaning NO_LED is True  
NO_LED=1 BUTTON

# Setting up a new LED pattern after the Button has been pressed (White Fast)
LED W FAST
