#!/bin/bash

# Title: An Advanced Button Payload 
#
# Description: A more advanced button payload that will use the button to change the LED pattern based on how many times the button was pressed on the Packet Squirrel
#
# Author: @H311oWoR1d1337 
#
# Props: Michael Kershaw

# Setting the Squirrel's Network Mode to NAT
NETMODE NAT

# Setting the LED to start as Yellow and flash with Inverted Quintuple Blink 
LED Y IQUIN

# Setting the button to wait for 5 seconds after boot-up for a press and have it not affect the LED using the environment variable NO_LED=1 meaning NO_LED is True.
# If the button was pressed before 5 seconds the LED will flash Cyan in Fast mode. If not, then the LED will flash Red in Very Fast Mode.
NO_LED=1 BUTTON 5 && {
  LED C FAST
} || { 
  LED R VERYFAST
}
